######################################################################
# Automatically generated by qmake (2.01a) ? 11? 6 21:06:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
