######################################################################
# Automatically generated by qmake (2.01a) ? 11? 9 17:25:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.hpp
SOURCES += main.cpp
